### ISSUE TITLE
[WinError 10061] No connection could be made because the target machine actively refused it

### ISSUE THREAD

**Issue by rootapis** [0vercl0k/paracosme#2]
python src\paracosme.py --target 127.0.0.1
Traceback (most recent call last):
  File "C:\Users\user\Desktop\cve\paracosme-main\src\paracosme.py", line 362, in <module>
    main()
  File "C:\Users\user\Desktop\cve\paracosme-main\src\paracosme.py", line 338, in main
    s = socket.create_connection((args.target, args.port))
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\socket.py", line 845, in create_connection
    raise err
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\socket.py", line 833, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it

**Comment by 0vercl0k** [comment]
It seems like there is no listening socket on 127.0.0.1, you probably haven't properly installed the target. Please verify that the targeted process is running :)

Closing.

Cheers
